/**
 * Prototype copy for the units workspace, Russian only. The production slice moves every key
 * into `@vakhta/i18n` (uk/en/ru); this file exists so the prototype can be evaluated before
 * three catalogs are touched. Existing catalog keys are reused where the prototype needs them.
 */
export const text = {
  title: 'Подразделения',
  summary: {
    units: 'Подразделений',
    employees: 'Сотрудников',
    unassigned: 'Без подразделения',
    withoutMaster: 'Без мастера',
    attention: 'Требуют внимания',
  },
  filters: {
    all: 'Все',
    attention: 'Требуют внимания',
    site: 'Площадка',
    allSites: 'Все площадки',
  },
  search: {
    label: 'Поиск',
    placeholder: 'Сотрудник или подразделение',
    people: 'Сотрудники',
    units: 'Подразделения',
    noResults: 'Ничего не найдено',
    inUnit: 'в',
    unassigned: 'без подразделения',
  },
  list: {
    heading: 'Подразделения',
    unassigned: 'Без подразделения',
    unassignedHint: 'Сотрудники, у которых нет текущей должности. Их не видно в графике и бонусе.',
    people: '{n} чел.',
    noUnits: 'Подразделений ещё нет',
    noUnitsHint: 'Создайте первое подразделение, затем распределите по нему сотрудников.',
    noneMatch: 'Нет подразделений, требующих внимания',
    noneMatchSearch: 'Подразделений с таким названием нет',
  },
  attention: {
    NO_MASTER: 'Мастер не назначен',
    MASTER_INACTIVE: 'Мастер неактивен',
    inactiveShort: 'неактивен',
    MASTER_ELSEWHERE: 'Мастер работает в другом подразделении',
    NO_EMPLOYEES: 'Нет сотрудников',
    noMasterHint:
      'Некому принимать отчёты о сдаче смены и решать инциденты. Назначьте мастера смены.',
    inactiveHint: 'Назначенный мастер заблокирован или уволен. Замените его.',
    elsewhereHint: 'Мастер числится в «{unit}». Проверьте, кто отвечает за это подразделение.',
    noEmployeesHint:
      'В подразделении никто не числится. Переместите сюда сотрудников или удалите его.',
  },
  master: {
    heading: 'Мастер смены',
    assign: 'Назначить мастера',
    replace: 'Заменить',
    clear: 'Убрать назначение',
    pick: 'Выберите мастера',
    fromUnit: 'Из этого подразделения',
    others: 'Другие сотрудники',
    hint: 'Мастер смены получает эскалации, принимает сдачу смены и подтверждает чек-листы. Назначение не даёт доступ к панели — роль выдаётся в «Пользователи и роли».',
    worksIn: 'работает в «{unit}»',
  },
  unit: {
    site: 'Площадка',
    parent: 'Входит в',
    children: 'Вложенные подразделения',
    teams: 'Бригады',
    zones: 'Зоны',
    zonesCount: '{n} зон',
    shifts: 'Смены подразделения',
    edit: 'Изменить',
    addChild: 'Добавить вложенное',
    delete: 'Удалить',
    deleteBlocked: 'Сначала переместите сотрудников и вложенные подразделения',
    deleteBlockedHistory:
      'Подразделение с историей смен и графиков нельзя удалить; его можно только архивировать.',
    employees: 'Сотрудники',
    noEmployees: 'В подразделении нет сотрудников',
    noEmployeesHint:
      'Переместите сюда людей из другого подразделения или из списка «Без подразделения».',
    goUnassigned: 'К нераспределённым',
    create: 'Подразделение',
    created: 'Подразделение создано.',
    name: 'Название',
    saveChanges: 'Сохранить',
    cancel: 'Отмена',
    add: 'Добавить',
    nested: 'Вложенное подразделение',
    noParent: 'Нет (корневое)',
    masterOptional: 'Можно назначить позже',
    viewOnly: 'Только просмотр',
    viewOnlyHint: 'Изменять структуру может администратор с областью этой площадки.',
  },
  people: {
    name: 'Сотрудник',
    number: 'Таб. №',
    position: 'Должность',
    team: 'Бригада',
    status: 'Статус',
    noPosition: 'Должность не назначена',
    noTeam: '—',
    move: 'Переместить в…',
    assign: 'Назначить в…',
    profile: 'Профиль',
    makeMaster: 'Сделать мастером смены',
    selected: 'Выбрано: {n}',
    moveSelected: 'Переместить выбранных',
    assignSelected: 'Назначить выбранных',
    clearSelection: 'Снять выделение',
    total: 'Всего: {n}',
    since: 'В системе с',
    action: 'Действие',
    noUnassigned: 'Все сотрудники распределены по подразделениям',
    noUnassignedHint:
      'Новые люди появятся здесь после импорта или создания карточки без должности.',
    unassignedWhy:
      'Без должности сотрудник не попадает в график, не может отметить приход и не учитывается в бонусе.',
  },
  move: {
    title: 'Переместить в подразделение',
    assignTitle: 'Назначить в подразделение',
    searchUnit: 'Найти подразделение',
    position: 'Должность',
    keepPosition: 'Должность сохраняется: {position}',
    choosePosition: 'Должность в новом подразделении',
    pickPosition: 'Выберите должность',
    team: 'Бригада',
    noTeam: 'Без бригады',
    teamReset: 'Бригада сбрасывается: в новом подразделении бригады другие.',
    from: 'Сейчас',
    to: 'Куда',
    confirm: 'Переместить',
    confirmAssign: 'Назначить',
    confirmMany: 'Переместить {n} чел.',
    confirmAssignMany: 'Назначить {n} чел.',
    effective: 'С текущего момента. Запланированные смены остаются в прежнем подразделении.',
    sameUnit: 'Уже здесь',
    done: 'Перемещено: {n}',
    partial: 'Перемещено {done} из {total}. Не удалось: {failed}.',
    failedRow: 'Не удалось переместить',
    retry: 'Повторить',
    current: 'Текущее',
  },
  states: {
    loading: 'Загружаем структуру…',
    error: 'Не удалось загрузить структуру',
    retry: 'Повторить',
    saving: 'Сохраняем…',
  },
  statuses: {
    ACTIVE: 'Активен',
    BLOCKED: 'Заблокирован',
    TERMINATED: 'Уволен',
  },
} as const;

export function fill(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ''));
}
