/**
 * Prototype copy for the structure section, Russian only. The production slice moves every key
 * into `@vakhta/i18n` (uk/en/ru); this file exists so the prototype can be evaluated before
 * three catalogs are touched. Existing catalog keys are reused where the prototype needs them.
 */
export const text = {
  title: 'Оргструктура',
  summary: {
    units: 'Подразделений',
    employees: 'Сотрудников',
    unassigned: 'Без подразделения',
    attention: 'Требуют внимания',
  },
  filters: {
    all: 'Все',
    attention: 'Требуют внимания',
    site: 'Площадка',
    allSites: 'Все площадки',
    archived: 'Показать архивные',
  },
  search: {
    label: 'Поиск',
    placeholder: 'Сотрудник или подразделение',
    people: 'Сотрудники',
    noResults: 'Ничего не найдено',
    unassigned: 'без подразделения',
  },
  kinds: {
    DIVISION: 'Подразделение',
    SHOP: 'Цех',
    SECTION: 'Участок',
  },
  list: {
    heading: 'Структура',
    unassigned: 'Без подразделения',
    unassignedHint:
      'Сотрудники, у которых нет текущей должности. Их не видно в графике, бонусе и будущем расчёте зарплаты.',
    people: '{n} чел.',
    noUnits: 'Подразделений ещё нет',
    noUnitsHint: 'Создайте первое подразделение, затем цеха и участки внутри него.',
    noneMatch: 'Нет подразделений, требующих внимания',
    noneMatchSearch: 'Подразделений с таким названием нет',
    collapse: 'Свернуть',
    expand: 'Развернуть',
  },
  attention: {
    NO_HEAD: 'Нет руководителя',
    NO_SHIFT_MASTER: 'Не все мастера смен назначены',
    RESPONSIBLE_INACTIVE: 'Ответственный неактивен',
    RESPONSIBLE_ELSEWHERE: 'Ответственный работает в другом подразделении',
    NO_EMPLOYEES: 'Нет сотрудников',
    inactiveShort: 'неактивен',
    noHeadHint:
      'Некому согласовывать заявки и отвечать за подразделение в отчётах. Назначьте руководителя.',
    noMasterHint:
      'Сдачу смены и эскалации примет руководитель, затем начальник производства. Назначьте мастеров обеих смен.',
    inactiveHint: 'Ответственный заблокирован или уволен. Замените его.',
    elsewhereHint:
      '{name} числится в «{unit}». Это допустимо, но проверьте, кто отвечает за это подразделение.',
    noEmployeesHint:
      'В подразделении никто не числится. Переместите сюда сотрудников или архивируйте его.',
  },
  slots: {
    heading: 'Ответственные',
    HEAD: 'Руководитель',
    SHIFT_MASTER_DAY: 'Мастер дневной смены',
    SHIFT_MASTER_NIGHT: 'Мастер ночной смены',
    hint: 'Руководитель согласовывает заявки и отвечает за подразделение в отчётах. Мастера смен принимают сдачу смены, эскалации и чек-листы. Назначение не даёт доступ к панели — роль выдаётся в «Пользователи и роли».',
    assign: 'Назначить',
    replace: 'Заменить',
    clear: 'Убрать',
    pick: 'Выберите сотрудника',
    fromUnit: 'Из этого подразделения',
    others: 'Другие сотрудники',
    worksIn: 'работает в «{unit}»',
    since: 'с {date}',
    inherited: 'по наследству от «{unit}»',
    missing: 'Не назначен',
  },
  unit: {
    site: 'Площадка',
    parent: 'Входит в',
    kind: 'Тип',
    children: 'Вложенные',
    teams: 'Бригады',
    zonesCount: '{n} зон',
    validFrom: 'Действует с',
    effectiveFrom: 'с {date}',
    shifts: 'Смены',
    edit: 'Изменить',
    addChild: 'Добавить вложенное',
    moveNode: 'Перенести',
    history: 'История изменений',
    archive: 'Архивировать',
    archived: 'В архиве',
    archiveBlocked: 'Сначала переместите сотрудников и вложенные подразделения',
    archiveHint:
      'Архивное подразделение скрыто из выбора и графика, но остаётся в истории, отчётах и расчётах за прошлые периоды.',
    employees: 'Сотрудники',
    noEmployees: 'В подразделении нет сотрудников',
    noEmployeesHint:
      'Переместите сюда людей из другого подразделения или из списка «Без подразделения».',
    goUnassigned: 'К нераспределённым',
    create: 'Подразделение',
    created: 'Подразделение создано.',
    name: 'Название',
    cancel: 'Отмена',
    add: 'Добавить',
    noParent: 'Нет (верхний уровень)',
    headOptional: 'Можно назначить позже',
    viewOnly: 'Только просмотр',
    historyEmpty: 'Изменений ещё не было',
  },
  people: {
    name: 'Сотрудник',
    position: 'Должность',
    team: 'Бригада',
    manager: 'Руководитель',
    noPosition: 'Должность не назначена',
    noTeam: '—',
    move: 'Переместить в…',
    assign: 'Назначить в…',
    profile: 'Профиль',
    makeHead: 'Сделать руководителем',
    selected: 'Выбрано: {n}',
    moveSelected: 'Переместить выбранных',
    assignSelected: 'Назначить выбранных',
    total: 'Всего: {n}',
    since: 'В системе с',
    action: 'Действие',
    noUnassigned: 'Все сотрудники распределены по подразделениям',
    noUnassignedHint:
      'Новые люди появятся здесь после импорта или создания карточки без должности.',
    unassignedWhy:
      'Без должности сотрудник не попадает в график, не может отметить приход и не учитывается в бонусе.',
  },
  move: {
    title: 'Переместить в подразделение',
    assignTitle: 'Назначить в подразделение',
    searchUnit: 'Найти подразделение',
    keepPosition: 'Должность сохраняется: {position}',
    choosePosition: 'Должность в новом подразделении',
    pickPosition: 'Выберите должность',
    team: 'Бригада',
    noTeam: 'Без бригады',
    teamReset: 'Бригада сбрасывается: в новом подразделении бригады другие.',
    date: 'Дата перевода',
    dateHint:
      'С этой даты сотрудник числится в новом подразделении для графика, бонуса и отчётов. Запланированные смены остаются в прежнем.',
    confirm: 'Переместить',
    confirmAssign: 'Назначить',
    confirmMany: 'Переместить {n} чел.',
    confirmAssignMany: 'Назначить {n} чел.',
    sameUnit: 'Уже здесь',
    done: 'Перемещено: {n}',
  },
  payTerms: {
    heading: 'Условия оплаты',
    hint: 'Группы оплаты, действующие в этом подразделении: свои и унаследованные от подразделений выше. Суммы видны в карточке сотрудника; здесь — кто и какой версией платится.',
    empty: 'Группы оплаты не подключены: сотрудники получают условия центра.',
    group: 'Группа оплаты',
    source: 'Источник',
    version: 'Версия',
    coverage: 'Назначений',
    own: 'Задано здесь',
    inheritedFrom: 'от «{unit}»',
    since: 'с {date}',
    draft: 'черновик v{n}',
    assignments: '{n}',
    people: '· {n} чел.',
    whereUsed: 'Где используется',
  },
  states: {
    loading: 'Загружаем структуру…',
    error: 'Не удалось загрузить структуру',
  },
  statuses: {
    ACTIVE: 'Активен',
    BLOCKED: 'Заблокирован',
    TERMINATED: 'Уволен',
  },
} as const;

export function fill(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ''));
}
